kafka:
  hosts: 192.168.11.12:9092,192.168.11.13:9092,192.168.11.14:9092
  # debezium监控mongo对应topic的数据
  faceProfileTopic: mongo-shard-test3.yisa_oe.face_group_test
  faceProfilePlateTopic: mongo-shard.yisa_oe.face_group_plate
  groupId: face-profile-synchronizing-20221219
  # 偏移量策略,earliest,latest
  # (同一组id，第一次启动为earliest，后面设置为latest)
  offset: latest

lightningDB:
  hosts:
    - [ '192.168.11.12', 8123 ]
    - [ '192.168.11.13', 8123 ]
  # 用户名 默认: default
  username: bigdata
  # 密码 默认: ''
  password: bigdata-fusion3.0
  # 数据库
  database: yisa_oe
  # 档案分布式表
  faceProfileDistributedTable: face_profile_insert_all
  # 驾乘档案分布式表
  faceProfilePlateDistributedTable: face_profile_plate_insert_all
  # 每一批最大插入的数据量
  batchSize: 10000
  # 刷新间隔期间(毫秒)
  flushInterval: 1000
  # 最大重试次数
  maxRetries: 3

arangoDB:
  hosts:
    - ['192.168.11.13', 8529]
  username: 'root'
  password: 'yisa123456'
  database: 'yisa_personnel'
  # 关系表（边表）
  relationEdgeTable: personnel_relation
  # 驾乘人脸聚类档案表
  faceProfilePlateTable: face_profile_plate
  # 人脸聚类档案表
  faceProfileTable: face_profile
  # 人员基本信息
  personnelInfoTable: personnel_info
  #  标签表
  labelTable: label_info

parameter:
  # 检查点间隔时间(毫秒)
  checkPoint: 10000
  # task级别错误重启 间隔时间
  delayBetweenAttempts: 10000
  # 是否禁用算子操作链
  disableOperatorChain: false
