kafka:
  hosts: 192.168.11.16:9092,192.168.11.17:9092,192.168.11.18:9092
  # debezium监控mongo对应topic的数据
  topic: mongo-compact.yisa_oe.face_profile
  group_id: face-profile-synchronizing-20230401
  # 偏移量策略,earliest,latest
  offset: earliest

lightningdb:
  hosts: 192.168.11.16:8123,192.168.11.17:8123,192.168.11.18:8123
  # 用户名 默认: default
  username: default
  # 密码 默认: ''
  password: wSqDxDAt
  # 数据库
  database: test
  # 档案分布式表
  face_profile_distributed_table: face_profile
  # 每一批最大插入的数据量
  batch_size: 10000
  # 刷新间隔期间(毫秒)
  flush_interval: 1000
  # 最大重试次数
  max_retries: 3

parameter:
  # 检查点间隔时间(毫秒)
  check_point: 10000
  # task级别错误重启 间隔时间
  delay_between_attempts: 10000
  # 是否禁用算子操作链
  disable_operator_chain: false
