mongodb:
  hosts: "192.168.11.16:30001,192.168.11.16:30002,192.168.11.16:30003"
  # mongo聚类档案数据库
  database: yisa_oe
  # mongo聚类档案集合
  collection: face_profile
  username: flinkuser
  password: flinkpw

lightningdb:
  hosts: 192.168.11.16:8123,192.168.11.17:8123,192.168.11.18:8123,192.168.11.19:8123,192.168.11.20:8123
  # 用户名 默认: default
  username: default
  # 密码 默认: ''
  password: wSqDxDAt
  # 数据库
  database: test
  # 档案分布式表
  face_profile_distributed_table: face_profile_all
  # 每一批最大插入的数据量
  batch_size: 5000
  # 刷新间隔期间(毫秒)
  flush_interval: 1000
  # 最大重试次数
  max_retries: 3


parameter:
  # checkpoint 间隔时间(毫秒)
  checkpointing_interval: 3000
